"INSERT INTO egypt.elephantine 
        (locusNum, objectGroupNum, 
            objectNum, numberOfObjects, 
            typeDescription, typeNum, 
            weight, fabric, 
            diamter, preservations,
            sfCoating, sfTreatment, 
            blackened, incisedDecoration, 
            application, paintedDecoration, 
            comments, photo, 
            processedBy, processedDate, 
            enteredBy, enteredDate, 
            rlNum, sheetNum, 
            lat, lng, 
            room, phase) VALUES 
            ('undefined', 'undefined', 
            'undefined','1',
            'Hem cups','undefined',
            'null','null',
            'undefined','undefined',
            'null','null',
            'null','null',
            'null','null',
            'null','null',
            'null','undefined',
            'null','null',
            'undefined','undefined',
            'undefined','undefined',
            'undefined','undefined');"